defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "bariumsulfida"
      permalink: /:title
  - scope:
      path: ""
    values:
      layout: "default"

domain: bariumsulfida.github.io/       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://bariumsulfida.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /      # place folder name if the site is served in a subfolder